development: &default
  host: <%= ENV['database_host'] %>
  port: <%= ENV['database_port'] %>
  adapter: postgresql
  database: <%= ENV['database_name'] %>
  username: <%= ENV['database_username'] %>
  password: <%= ENV['database_password'] %>
  pool: 25

test:
  <<: *default

production:
  <<: *default
  host: localhost
  post: 5432
